
# Site Settings
title: McKay Maille
email: mckaymaille@gmail.com
description: Welcome to my chainmaille showcase and blog. I hope you enjoy what you see and learn a lot here. 
github_username:  moaatt2
baseurl: ""
url: ""

# Minima Settings
remote_theme: moaatt2/minima@master
minima:
  skin: dark
  social_links:
    - platform: github
      user_url: https://github.com/moaatt2
      user_title: GitHub

    - platform: rss
      user_url: "/feed.xml"
      user_title: "RSS Feed"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
