
# Site Settings
title: McKay Maille
email: mckaymaille@gmail.com
description: Welcome to my chainmaille showcase and blog. I hope you enjoy what you see and learn a lot here. 
github_username:  moaatt2
baseurl: ""
url: ""

# Minima Settings
remote_theme: moaatt2/minima@master
minima:
  skin: dark

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
